### ISSUE TITLE
Expand on description

### ISSUE THREAD

**Issue by slarse** [IndaProjekt/indaproj#17]
You seem to be off to a good start!

I just want you to expand a little bit on your description.

1. Specify the framework(s) and any libraries you will be using.
2. Give an example of a transformation and, in broad terms, how it affects the image. This is really the main part of your program so it should be clearly exemplified.

**Comment by ChristofferAlenskogBerg** [comment]
We have updated the description now

**Comment by slarse** [comment]
@ChristofferAlenskogBerg That's a lot more informative, nice!
